name: azure-openai-proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-:
    uses: ./.github/workflows/deploy.yml
    with:
      environmentType: Production
      resourceGroupName: rg-DOZAKA
      reviewApiUrl: ${{ secrets.REVIEW_API_URL }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY }}
